# Generated by Django 6.0.5 on 2026-06-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_serviceaddress_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='affected_addresses',
            field=models.ManyToManyField(blank=True, to='core.serviceaddress', verbose_name='Адреси, що потрапили під відключення'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(verbose_name='Опис інциденту'),
        ),
    ]
