# Generated by Django 6.0.5 on 2026-05-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boilerroom_boiler_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilerroom',
            name='boiler_type',
            field=models.CharField(choices=[('scheme_1', 'Схема 1 (a-d)'), ('scheme_2', 'Схема 2 (a-d)'), ('scheme_9', 'Схема 9 (a-d)'), ('scheme_10', 'Схема 10 / 10c')], default='scheme_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='boilerroom',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('maintenance', 'Обслуговування'), ('error', 'Помилка')], default='active', max_length=20),
        ),
    ]
