# Generated by Django 6.0.5 on 2026-05-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_boilerroom_boiler_type_alter_boilerroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Температура'), ('pressure', 'Тиск'), ('flow', 'Витрата')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceaddress',
            name='status',
            field=models.CharField(choices=[('normal', 'Норма'), ('no_heating', 'Немає опалення'), ('no_hot_water', 'Немає гарячої води'), ('disconnected', 'Відключено')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Адміністратор'), ('engineer', 'Інженер'), ('client', 'Клієнт')], default='client', max_length=20),
        ),
        migrations.AlterModelTable(
            name='boilerroom',
            table='boiler_rooms',
        ),
        migrations.AlterModelTable(
            name='incident',
            table='incidents',
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='sensors',
        ),
        migrations.AlterModelTable(
            name='serviceaddress',
            table='service_addresses',
        ),
    ]
