# Generated by Django 6.0.5 on 2026-05-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sensor_sensor_type_alter_serviceaddress_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaddress',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар інженера'),
        ),
    ]
