# Generated by Django 6.0.5 on 2026-05-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_device_status_alter_devicestatushistory_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='devices',
        ),
        migrations.AlterModelTable(
            name='devicecategory',
            table='device_categories',
        ),
        migrations.AlterModelTable(
            name='devicestatushistory',
            table='device_status_history',
        ),
        migrations.AlterModelTable(
            name='sensorreading',
            table='sensor_readings',
        ),
    ]
