# Generated by Django 6.0.5 on 2026-05-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('green', 'Норма'), ('yellow', 'Увага'), ('red', 'Аварія'), ('black', 'Вимкнено')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='devicestatushistory',
            name='status',
            field=models.CharField(choices=[('green', 'Норма'), ('yellow', 'Увага'), ('red', 'Аварія'), ('black', 'Вимкнено')], max_length=10),
        ),
    ]
